channels:
- conda-forge
dependencies:
- python=3.11.10
- pip
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - feast==0.50.0
  - google-cloud-bigquery==3.35.1
  - google-cloud-storage==3.2.0
  - gunicorn==23.0.0
  - numpy==2.2.6
  - pandas==2.3.1
  - pyarrow==17.0.0
  - python-dotenv==1.1.1
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - sqlalchemy==2.0.41
  - watchfiles==1.1.0
name: mlflow-env
