channels:
- conda-forge
dependencies:
- python=3.11.10
- pip
- pip:
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.12.14
  - aiosignal==1.4.0
  - alembic==1.16.4
  - annotated-types==0.7.0
  - anyio==4.9.0
  - attrs==25.3.0
  - bigtree==0.29.2
  - blinker==1.9.0
  - boto3==1.39.4
  - botocore==1.39.4
  - cachetools==5.5.2
  - catboost==1.2.8
  - category-encoders==2.8.1
  - certifi==2025.7.14
  - charset-normalizer==3.4.2
  - click==8.2.1
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - colorlog==6.9.0
  - contourpy==1.3.2
  - cycler==0.12.1
  - dask==2025.7.0
  - db-dtypes==1.4.3
  - decorator==5.2.1
  - dill==0.3.9
  - docker==7.1.0
  - entrypoints==0.4
  - fastapi==0.116.1
  - feast==0.47.0
  - filelock==3.18.0
  - flask==3.1.1
  - fonttools==4.58.5
  - frozenlist==1.7.0
  - fsspec==2025.5.1
  - gcsfs==2025.5.1
  - gitdb==4.0.12
  - gitpython==3.1.44
  - google-api-core==2.25.1
  - google-auth==2.40.3
  - google-auth-oauthlib==1.2.2
  - google-cloud-bigquery==3.35.1
  - google-cloud-core==2.4.3
  - google-cloud-storage==3.2.0
  - google-crc32c==1.7.1
  - google-resumable-media==2.7.2
  - googleapis-common-protos==1.70.0
  - graphene==3.4.3
  - graphql-core==3.2.6
  - graphql-relay==3.2.0
  - graphviz==0.21
  - grimp==3.9
  - grpcio==1.74.0
  - grpcio-status==1.62.3
  - gunicorn==22.0.0
  - h11==0.16.0
  - httpcore==1.0.9
  - httptools==0.6.4
  - httpx==0.28.1
  - idna==3.10
  - import-linter==2.3
  - importlib-metadata==7.2.1
  - iniconfig==2.1.0
  - itsdangerous==2.2.0
  - jinja2==3.1.6
  - jmespath==1.0.1
  - joblib==1.5.1
  - jsonschema==4.24.0
  - jsonschema-specifications==2025.4.1
  - kiwisolver==1.4.8
  - lightgbm==4.6.0
  - llvmlite==0.44.0
  - locket==1.0.0
  - mako==1.3.10
  - markdown==3.8.2
  - markdown-it-py==3.0.0
  - markupsafe==3.0.2
  - matplotlib==3.10.3
  - mdurl==0.1.2
  - mlflow==2.13.2
  - mmh3==5.1.0
  - -e file:///Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline
  - mpmath==1.3.0
  - multidict==6.6.3
  - mypy==1.17.0
  - mypy-extensions==1.1.0
  - narwhals==1.47.0
  - networkx==3.5
  - numba==0.61.2
  - numpy==1.26.4
  - oauthlib==3.3.1
  - opentelemetry-api==1.35.0
  - opentelemetry-sdk==1.35.0
  - opentelemetry-semantic-conventions==0.56b0
  - optuna==4.4.0
  - packaging==24.2
  - pandas==2.3.1
  - partd==1.4.2
  - pathspec==0.12.1
  - patsy==1.0.1
  - pillow==11.3.0
  - plotly==6.2.0
  - pluggy==1.6.0
  - prometheus-client==0.22.1
  - propcache==0.3.2
  - proto-plus==1.26.1
  - protobuf==4.25.8
  - psutil==7.0.0
  - psycopg==3.2.9
  - psycopg2-binary==2.9.10
  - py-dotenv==0.1
  - pyarrow==15.0.2
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pydantic==2.11.7
  - pydantic-core==2.33.2
  - pygments==2.19.2
  - pyjwt==2.10.1
  - pyparsing==3.2.3
  - pytest==8.4.1
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.1.1
  - pytz==2024.2
  - pyyaml==6.0.2
  - querystring-parser==1.2.4
  - redis==6.2.0
  - referencing==0.36.2
  - requests==2.32.4
  - requests-oauthlib==2.0.0
  - rich==14.0.0
  - rpds-py==0.26.0
  - rsa==4.9.1
  - rtdl-revisiting-models==0.0.2
  - ruff==0.12.3
  - s3fs==0.4.2
  - s3transfer==0.13.0
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - setuptools==75.3.2
  - shap==0.48.0
  - shellingham==1.5.4
  - six==1.17.0
  - slicer==0.0.8
  - smmap==5.0.2
  - sniffio==1.3.1
  - sqlalchemy==2.0.41
  - sqlparse==0.5.3
  - starlette==0.47.1
  - statsmodels==0.14.5
  - sympy==1.14.0
  - tabulate==0.9.0
  - tenacity==8.5.0
  - threadpoolctl==3.6.0
  - toml==0.10.2
  - toolz==1.0.0
  - torch==2.7.1
  - tqdm==4.67.1
  - typeguard==4.4.4
  - typer==0.16.0
  - typing-extensions==4.14.1
  - typing-inspection==0.4.1
  - tzdata==2025.2
  - urllib3==2.5.0
  - uv==0.8.8
  - uvicorn==0.35.0
  - uvicorn-worker==0.3.0
  - uvloop==0.21.0
  - watchfiles==1.1.0
  - websockets==15.0.1
  - werkzeug==3.1.3
  - xgboost==3.0.2
  - yarl==1.20.1
  - zipp==3.23.0
name: mlflow-env
